Niran/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WebEcom.urls')),
    path('', include('adminlte.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminlte/urls.py
from django.contrib import admin
from django.urls import path, include
from adminlte import views

urlpatterns = [
    path('home', views.home, name='home'),
    path('login', views.signin, name='login'),
     path('sale', views.sale, name='sale'),
      path('product', views.product, name='product'),
       path('addproduct', views.addproduct, name='addproduct'),
        path('editproduct/<int:product_id>', views.editproduct, name='editproduct'),
]

WebEcom/models.py
from django.db import models
import os
# Create your models here.
class Product(models.Model):
    Product_id =  models.AutoField(primary_key=True)
    Product_Code = models.CharField(max_length=255)
    Product_Price = models.IntegerField()
    Product_Detial = models.CharField(max_length=255)
    Is_active = models.BooleanField(default=True)
    def __str__(self):
        return self.Product_Code
class Product_Img(models.Model):
    Product_Img_id =  models.AutoField(primary_key=True)
    Product = models.ForeignKey(Product,on_delete=models.CASCADE)
    Product_Img =  models.ImageField(upload_to='reports/')  # 'reports/' is the directory where images will be stored
    def __str__(self):
        return self.Product.Product_Code
    def delete(self, *args, **kwargs):
        # Delete the associated image file before deleting the model instance
        if self.Product_Img:
            image_path = self.Product_Img.path
            if os.path.exists(image_path):
                os.remove(image_path)
        super().delete(*args, **kwargs)
class Token_Line(models.Model):
    Token_id =  models.AutoField(primary_key=True)
    Token_Code = models.CharField(max_length=255)
    def __str__(self):
        return self.Token_Code

adminlte/models.py
from django.db import models

# Create your models here.

adminlte/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from WebEcom.models import *
from django.http import JsonResponse
# Create your views here.
# Create your views here.
def signin(request):
    if request.method == 'POST':
        print(request.POST)
        username = request.POST['username']
        pass1 = request.POST['pass1']
        
        user = authenticate(username=username, password=pass1)
        
        if user is not None:
            login(request, user)
            fname = user.first_name
            # messages.success(request, "Logged In Sucessfully!!")
            print(fname)
            return redirect('home')
        
        else:
            messages.error(request, "Username หรือ Password ไม่ถูกต้อง")
            return redirect('signin')
    if request.user.is_authenticated:
        return redirect('home')
    return render(request, "adminlte/login.html")
def home(request):
    if request.user.is_authenticated:
        pass
    else:
        return redirect('login')
    return render(request, "adminlte/dashborad.html")
def sale(request):
    if request.user.is_authenticated:
        pass
    else:
        return redirect('login')
    return render(request, "adminlte/Sale.html")
def product(request):
    if request.user.is_authenticated:
        pass
    else:
        return redirect('login')
    if request.method == "POST":
        print(request.POST)
        try:
            Product_ = Product.objects.get(Product_id=request.POST['remove_id'])
            Product_img_ = Product_Img.objects.filter(Product = Product_)
            for i in Product_img_:
                image_path = i.Product_Img.path
                if os.path.exists(image_path):
                    os.remove(image_path)
            Product_.delete()
            return JsonResponse({"data":"ok"},status=200) 
        except Exception as e:
            return JsonResponse({"data":"ng","msg":"remove_error"},status=200) 
        
    proudct_list = Product.objects.all()
    proudct_list = proudct_list.filter(Is_active = True)
    return render(request, "adminlte/product.html",{"list_product":proudct_list})
def addproduct(request):
    if request.user.is_authenticated:
        pass
    else:
        return redirect('login')
    if request.method == "POST":
        print(request.POST)
        data = request.POST
        files = request.FILES 
        Product_ = Product()
        Product_.Product_Code = data['Product_Code']
        Product_.Product_Detial = data['Product_Detial']
        Product_.Product_Price = data['Product_Price']
        Product_.save()
        Product_Img_ = Product_Img()
        Product_Img_.Product = Product_
        Product_Img_.Product_Img = files['imgReport']
        Product_Img_.save()
        # try:
        #     Product_Img_ = Product_Img_()
        #     Product_Img_.Product = Product_
        #     Product_Img_.Product_Img = files['imgReport2']
        #     Product_Img_.save()
        # except:
        #     pass
        


        print(files)
        return redirect('product')
    return render(request, "adminlte/addproduct.html")
def editproduct(request,product_id):
    if request.user.is_authenticated:
        pass
    else:
        return redirect('login')
    if request.method == "POST":
        print(request.POST)
        data = request.POST
        files = request.FILES 
        print(files)
        Product_ = Product.objects.get(Product_id = product_id)
        Product_.Product_Code = data['Product_Code']
        Product_.Product_Detial = data['Product_Detial']
        Product_.Product_Price = data['Product_Price']
        if data['customCheck'] == 'on':
             Product_.Is_active = True
        else:
            Product_.Is_active = False
        Product_.save()
        fil1 = None
        fil2 = None
        Product_img_ = Product_Img.objects.filter(Product = Product_)
        try:
            fil1 = files['imgReport']
            
        except:
            pass
        try:
            fil2 = files['imgReport2']
        except:
            pass
        print(fil1)
        print(fil2)
        if fil1 != None and fil2 != None:
            for i in Product_img_:
                image_path = i.Product_Img.path
                if os.path.exists(image_path):
                    os.remove(image_path)
                    i.delete()

            new_pic = Product_Img()
            new_pic.Product = Product_
            new_pic.Product_Img = fil1
            new_pic.save()
            new_pic = Product_Img()
            new_pic.Product = Product_
            new_pic.Product_Img = fil2
            new_pic.save()
        elif fil1 != None and fil2 == None:
  
            image_path = Product_img_.first().Product_Img.path
            if os.path.exists(image_path):
                os.remove(image_path)
                Product_img_.first().delete()
            new_pic = Product_Img()
            new_pic.Product = Product_
            new_pic.Product_Img = fil1
            new_pic.save()
        elif fil1 == None and fil2 != None:
            if len(Product_img_) != 1:
                image_path = Product_img_.last().Product_Img.path
                if os.path.exists(image_path):
                    os.remove(image_path)
                    Product_img_.last().delete()
            
            new_pic = Product_Img()
            new_pic.Product = Product_
            new_pic.Product_Img = fil2
            new_pic.save()
        else:
            pass
   
    product_ = Product.objects.get(Product_id = product_id)
    product_img = Product_Img.objects.filter(Product= product_)
    return render(request, "adminlte/editproduct.html",{"product":product_,"img":product_img})

templates/adminlte/Sale.html
{% extends "adminlte/base.html" %}

{% block content %}
{% load static %}

<div id="main">

    <div class="page-content">
        <div class="page-heading">
            <h3>ประวัติการทำรายการขายล่าสุด</h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="home">หน้าหลัก</a></li>
         
                  <li class="breadcrumb-item active" aria-current="page"><a href="#">ประวัติการทำรายการขายล่าสุด</a></li>
                </ol>
              </nav>
        </div>
        
        <div class="page-content">
            
            <div class="card">
                <div class="card-header">
                  <h4>ตารางรายการงานและรายละเอียด</h4>
                  <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="fname">วันที่เริ่มต้น</label>
                            <input type="date" value="{{count.start}}" class="form-control" id="startdate" name="startdate"  Required>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="fname">วันที่สิ้นสุด</label>
                            <input type="date" value = "{{count.end}}"class="form-control" id="enddate" name="enddate"  Required>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary rounded-pill" style="margin:auto;" id="searchButton" onclick="fillter()">ค้นหาข้อมูล</button>
                <button class="btn btn-danger rounded-pill" style="margin:auto;" id="searchButton" onclick="location.reload()">ล้างการค้นหา</button>
           
                </div>
                <div class="card-body">
        
                  <table id="myTable" class="display">
                      <thead>
                          <tr>
                            <th>No</th>
                              <th>Type</th>
                              <th>Code</th>
                              <th>Job</th>
                              <th>Description</th>
                              <th>Note</th>
                            
                              <th>Status</th>
                              <th id="th_row1">Create Date</th>
                              <th id="th_row2">Complete Date</th>
                              <th>(min)</th>
                              <th id="th_row">User</th>
                              <th>Asgn</th>
                             
                          </tr>
                      </thead>
                      <tbody>
                        {% for i in list_job %}
                        <tr>
                           <td>{{ forloop.counter }}</td>
                          <td>{{i.Workdetail.WorkType.Worktype_name}}</td>
                          <td>{{i.Workdetail.Workdetail_Code}}</td>
                          <td>{{i.Customer.Customer_name}}</td>
                          <td>{{i.jobdetial}}</td>
                          <td>  {% if i.jobnote is None %}
                                
                            {% else %}
                                {{ i.jobnote }}
                            {% endif %}
                          </td>       
                          {% if i.status == 'NewTask'  %}
                          <td>  <span class="badge bg-danger">New</span></td>
                      
                        {% elif i.status == 'Done' %}
                            <!-- This content will be displayed if the condition is False -->
                            <td>  <span class="badge bg-success">Done</span></td>
                        {% else %}
                            <td>  <span class="badge bg-secondary">Cancel</span></td>
                        {% endif %}       
                         
                          <td>{{ i.create_at|date:"d/m/Y H:i" }}</td>
                          
                          <td>  {% if i.complete is None %}
                                
                                {% else %}
                                    {{ i.complete|date:"d/m/Y H:i" }} 
                                {% endif %}
                          </td>          
                          <td style="text-align: right">  {% if i.used is None %}
                                
                            {% else %}
                            {{ i.used|floatformat:0 }}
                            {% endif %}
                          </td>
                          <td>{{i.UserProfile.user.username}}</td>
                          <td>{{i.UserProfile_assignment.codename}}</td>
                           
                         
                      </tr>
                      {% endfor %}
                      </tbody>
                  </table>
                </div>
              </div>
        </div>


<script>
$(document).ready( function () {

    var now = new Date();
    now.setHours(now.getHours() + 7);
    // Format the date to match the datetime-local input format (YYYY-MM-DDTHH:mm)
    var formattedDate = now.toISOString().slice(0, 16);
    
    // Set the value of the input field
    $('#bdate').val(formattedDate);

    var table= $('#myTable').DataTable( {
       "pageLength": 50,
      columnDefs: [{ width: '12%', targets: [7,8] }],
      dom: 'Bfrtip',
      buttons: [
      {
        extend: 'excelHtml5',
        text: 'Excel',
        charset: 'UTF-8',
        // Other options and customization
    }
      ],
      responsive: true,
      rowReorder: {
        selector: 'td:nth-child(2)'
    }
    
    
  });  
  
  $('#myTable th#th_row').css('width', '20px');


});


function fillter () {
$.ajax({
url: '/todolist',
method: 'GET',
data: { action: 2 ,
      start: $("#startdate").val(),
      end: $("#enddate").val()
},
success: function(response) {
  // Handle the response from the server
  console.log( response);
  var dataTable = $('#myTable').DataTable();
  var cmd = 1;
  dataTable.clear().draw();
  response.list_job.forEach(function(element) {
    console.log(element); // Perform any action you want with each element
    var newData = []; // Replace with your actual data
    newData.push(cmd);
    cmd = cmd+1;
    newData.push(element.Workdetail__WorkType__Worktype_name)
    newData.push(element.Workdetail__Workdetail_Code)
    newData.push(element.Customer__Customer_name)
    newData.push(element.jobdetial)
    newData.push(element.jobnote)
    
    if(element.status == "NewTask"){
      newData.push('<span class="badge bg-danger">New</span>')
    }else if(element.status = "Done"){
      newData.push('<span class="badge bg-success">Done</span>')
    }else{
      newData.push('<span class="badge bg-secondary">Canncel</span>')
    }
    // Parse the original date string
    const originalDate = new Date(element.create_at);

    // Format the date to "DD/MM/YYYY HH:mm"
    const formattedDate = `${originalDate.getDate()}/${originalDate.getMonth() + 1}/${originalDate.getFullYear()} ${originalDate.getHours()}:${originalDate.getMinutes()}`;
    newData.push(formattedDate)
   
    if(element.complete == null){
      newData.push(element.complete)
    }else{
      const originalDate = new Date(element.complete);

      // Format the date to "DD/MM/YYYY"
      const formattedDate = `${originalDate.getDate()}/${originalDate.getMonth() + 1}/${originalDate.getFullYear()}`;
      newData.push(formattedDate);
    }
   
    newData.push(element.used)

    // newData.push('<div class="btn-group dropdown">'+
    //  '<a class="btn icon btn-primary" id="dropdownMenuOffset" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="bi bi-pencil"></i></a>'+
    //  '<div class="dropdown-menu" aria-labelledby="dropdownMenuOffset" >'+
    //    '<a class="dropdown-item" onclick="editTask('+ element.Workhis_id +')">แก้ไข</a>'+
     //   '<a class="dropdown-item" onclick="delete_data('+ element.Workhis_id +',\''+ element.Workdetail__Workdetail_Code +'\',\''+ formatDate(element.create_at) +'\')">ลบ</a>'+
     // '</div>')
     newData.push(element.UserProfile__user__username)
     newData.push(element.UserProfile_assignment__codename)
    dataTable.row.add(newData).draw();
  })


 // $("#Total").text(response.count.workhis_count+ " Unit");
 // $("#Done").text(response.count.workhis_count_done + " Unit");
 // $("#New").text(response.count.workhis_count_new+ " Unit");
//  $("#Cancel").text(response.count.workhis_count_cancel+" Unit");
},
error: function(xhr, status, error) {
  // Handle errors
  console.log("Error: " + error);
}
});
}
</script>
</div>

{% endblock content%}

templates/adminlte/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ระบบการจัดการงาน Task Management</title>

    <!-- <link rel="preconnect" href="https://fonts.gstatic.com"> -->
    <!-- <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Thai:wght@400;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'admin/assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'admin/assets/vendors/iconly/bold.css' %}">

    <link rel="stylesheet" href="{% static 'admin/assets/vendors/perfect-scrollbar/perfect-scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'admin/assets/vendors/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'admin/assets/css/app.css' %}">
    <link rel="shortcut icon" href="{% static 'admin/assets/images/favicon.svg" type="image/x-icon' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/TweenMax.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />
  
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>
    

</head>
<style>
    *{
        font-family: 'Noto Sans Thai', sans-serif;
    }
</style>

<body>
    <div id="app">
        <div id="sidebar" class="active">
            <div class="sidebar-wrapper active">
                <div class="sidebar-menu">
                    <ul class="menu">
                        <li class="sidebar-title"><a href="#">  ยินดีต้อนรับ !</a></li>
                        <li class="sidebar-title">ผู้ใช้งาน:</li> <span class="sidebar-title">{{ name }}</span>
                        <li class="sidebar-title">เมนู</li>
                        <li class="sidebar-item">
                            <a href="/home" class='sidebar-link'>
                                <i class="bi bi-journal-check"></i>
                                <span>Dashborad</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a href="/sale" class="sidebar-link">
                                <i class="bi bi-grid-fill"></i>
                                <span>Order</span>
                            </a>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a href="#" class="sidebar-link">
                                <i class="bi bi-pentagon-fill"></i>
                                <span>Products</span>
                            </a>
                            <ul class="submenu" style="display: none;">
                                <li class="submenu-item ">
                                 
                                    <a href="/product" >Product List</a>
                                </li>
                                <li class="submenu-item ">
                                 
                                    <a href="/addproduct">Add Product</a>
                                </li>
                            
                            </ul>
                        </li>
                        

                        <li class="sidebar-item  has-sub">
                            <a href="#" class="sidebar-link">
                                <i class="bi bi-pentagon-fill"></i>
                                <span>เมนูจัดการ</span>
                            </a>
                            <ul class="submenu" style="display: none;">
                                <li class="submenu-item ">
                                 
                                    <a href="/admin" target="_blank">Admin-site</a>
                                </li>
                                <li class="submenu-item ">
                                 
                                    <a href="/signout">ออกจากระบบ</a>
                                </li>
                            
                            </ul>
                        </li>
                    </ul>
                </div>
                <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
            </div>
        </div>

        <div class="wrapper" >
            {% block content %}


            {% endblock content%}
        </div>

     
    </div>

   
    <script src="{% static 'admin/assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'admin/assets/js/bootstrap.bundle.min.js' %}"></script>

    <script src="{% static 'admin/assets/vendors/apexcharts/apexcharts.js' %}"></script>
    <script src="{% static 'admin/assets/js/pages/dashboard.js' %}"></script>

    <script src="{% static 'admin/assets/js/main.js' %}"></script>
   
    <script src="{% static 'admin/js/main.js' %}"></script>
    <script src="{% static 'admin/js/alert.js' %}"></script>
    <script src="{% static 'admin/js/summation.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
</body>

</html>

templates/adminlte/product.html
{% extends "adminlte/base.html" %}

{% block content %}
{% load static %}
<style>
  /* Style for the modal */
  #myModal {
      display: none;
      position: fixed;
      z-index: 1;
      left: 0;
      top: 0;
      width: 100%;
      height: 100%;
      overflow: auto;
      background-color: rgb(0,0,0);
      background-color: rgba(0,0,0,0.9);
      padding-top: 60px;
  }

  /* Style for the modal content */
  .modal-content {
      margin: auto;
      display: block;
      width: 80%;
      max-width: 500px;
      position: relative;
  }

  /* Style for the close button */
  .close {
      color: #000000;
      position: absolute;
      top: 10px;
      right: 10px;
      font-size: 25px;
      cursor: pointer;
  }

  /* Style for the image in the modal */
  .modal-content img {
      width: 100%;
  }
</style>
<div id="main">

    <div class="page-content">
      
                    
        <div class="card">
            <div class="card-header">
              <h4>ตารางรายการงานและรายละเอียด</h4>
            <button class="btn btn-primary rounded-pill" style="margin:auto;" id="searchButton"onclick="window.location.href='/addproduct'">+ADD PRODUCT</button>
            </div>
            <div class="card-body">
    
              <table id="myTable" class="display">
                  <thead>
                      <tr>
                        <th>No</th>
                          <th>Product Code</th>
                          <th>Product Price</th>
                          <th>Product Detial</th>
                          <th>Photo</th>
                          <th>Status</th>
                          <th>ACTIONS</th>
                        
                         
                      </tr>
                  </thead>
                  <tbody>
                    {% for product in list_product %}
                    <tr>
                      <td>{{ forloop.counter }}</td>
                      <td>{{ product.Product_Code }}</td>
                      <td>{{ product.Product_Price }}</td>
                      <td>{{ product.Product_Detial }}</td>
                      <td><img src="{{product.product_img_set.first.Product_Img.url}}" alt="{{ product.Product_Code }} Image" width="50" height="auto;" onclick="showImage('{{product.product_img_set.first.Product_Img.url}}')"></td>
                      {% if product.Is_active == True %}
                      <td>  <span class="badge bg-success">Publish</span></td>
                
                      {% else %}
                          <td>  <span class="badge bg-danger">Inactive</span></td>
                      {% endif %}       
                     
                      
                      <td><div class="btn-group dropdown">
                        <a class="btn icon btn-primary" id="dropdownMenuOffset" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="bi bi-pencil"></i></a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset" >
                          <a class="dropdown-item" onclick="window.location.href='/editproduct/{{product.Product_id}}'">แก้ไข</a>
                          <a class="dropdown-item" onclick="delete_data({{product.Product_id}})">ลบ</a>
                        
                        </div>
                    </div></td>
                  </tr>
                  {% endfor %}
                  </tbody>
              </table>
            </div>
          </div>
   
    </div>
  

</div>

<div id="myModal" class="modal">
  <div class="modal-content">
      <span class="close" onclick="closeModal()">&times;</span>
      <img id="modalImage" src="" alt="Modal Image">
  </div>
</div>
<script>


  function delete_data(id){
    
    Swal.fire({
        title: 'ต้องการลบสินค้าหรือไม่?',
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'ลบข้อมูล',
        cancelButtonText: 'ยกเลิก'
      }).then((result) => {
        if (result.isConfirmed) {
          $.ajax({
            type: "POST",
            url: "/product", 
            dataType: 'json',
                async: false,
                //json object to sent to the authentication url
                data: {
                   csrfmiddlewaretoken: '{{ csrf_token }}' ,
                   "remove_id":id
                },
            success: function(data)
            {	
              console.log(data);
              if(data['data'] == 'ok'){
                Swal.fire({
                    icon: 'success',
                    title: 'Success',
                    text: 'ลบข้อมูลสำเร็จ',  // Display the first message
                    showConfirmButton: false, // This will remove the "OK" button
                });
                    // After 5 seconds, reload the page
                setTimeout(function () {
                    location.reload();
                }, 2000); // 3000 milliseconds = 3 seconds
              }else{
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: data['msg'],  // Display the first message
                    
                });
              }
              
            }
          });
        }
      });
   
  }
  function showImage(imageUrl) {
      var modal = document.getElementById('myModal');
      var modalImage = document.getElementById('modalImage');

      // Set the image source
      modalImage.src = imageUrl;

      // Display the modal
      modal.style.display = 'block';
  }

  function closeModal() {
      var modal = document.getElementById('myModal');
      modal.style.display = 'none';
  }
</script>
<script>
  $(document).ready( function () {

  var now = new Date();
  now.setHours(now.getHours() + 7);
  // Format the date to match the datetime-local input format (YYYY-MM-DDTHH:mm)
  var formattedDate = now.toISOString().slice(0, 16);

  // Set the value of the input field
  $('#bdate').val(formattedDate);

  var table= $('#myTable').DataTable( {
    
    dom: 'Bfrtip',
    buttons: [
    {
      extend: 'excelHtml5',
      text: 'Excel',
      charset: 'UTF-8',
      // Other options and customization
  }
    ],
    responsive: true,
    rowReorder: {
      selector: 'td:nth-child(2)'
  }


  });  

  $('#myTable th#th_row').css('width', '20px');


  });


  function fillter () {
  $.ajax({
  url: '/todolist',
  method: 'GET',
  data: { action: 2 ,
    start: $("#startdate").val(),
    end: $("#enddate").val()
  },
  success: function(response) {
  // Handle the response from the server
  console.log( response);
  var dataTable = $('#myTable').DataTable();
  var cmd = 1;
  dataTable.clear().draw();
  response.list_job.forEach(function(element) {
  console.log(element); // Perform any action you want with each element
  var newData = []; // Replace with your actual data
  newData.push(cmd);
  cmd = cmd+1;
  newData.push(element.Workdetail__WorkType__Worktype_name)
  newData.push(element.Workdetail__Workdetail_Code)
  newData.push(element.Customer__Customer_name)
  newData.push(element.jobdetial)
  newData.push(element.jobnote)

  if(element.status == "NewTask"){
    newData.push('<span class="badge bg-danger">New</span>')
  }else if(element.status = "Done"){
    newData.push('<span class="badge bg-success">Done</span>')
  }else{
    newData.push('<span class="badge bg-secondary">Canncel</span>')
  }
  // Parse the original date string
  const originalDate = new Date(element.create_at);

  // Format the date to "DD/MM/YYYY HH:mm"
  const formattedDate = `${originalDate.getDate()}/${originalDate.getMonth() + 1}/${originalDate.getFullYear()} ${originalDate.getHours()}:${originalDate.getMinutes()}`;
  newData.push(formattedDate)

  if(element.complete == null){
    newData.push(element.complete)
  }else{
    const originalDate = new Date(element.complete);

    // Format the date to "DD/MM/YYYY"
    const formattedDate = `${originalDate.getDate()}/${originalDate.getMonth() + 1}/${originalDate.getFullYear()}`;
    newData.push(formattedDate);
  }

  newData.push(element.used)

  // newData.push('<div class="btn-group dropdown">'+
  //  '<a class="btn icon btn-primary" id="dropdownMenuOffset" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="bi bi-pencil"></i></a>'+
  //  '<div class="dropdown-menu" aria-labelledby="dropdownMenuOffset" >'+
  //    '<a class="dropdown-item" onclick="editTask('+ element.Workhis_id +')">แก้ไข</a>'+
  //   '<a class="dropdown-item" onclick="delete_data('+ element.Workhis_id +',\''+ element.Workdetail__Workdetail_Code +'\',\''+ formatDate(element.create_at) +'\')">ลบ</a>'+
  // '</div>')
  newData.push(element.UserProfile__user__username)
  newData.push(element.UserProfile_assignment__codename)
  dataTable.row.add(newData).draw();
  })


  // $("#Total").text(response.count.workhis_count+ " Unit");
  // $("#Done").text(response.count.workhis_count_done + " Unit");
  // $("#New").text(response.count.workhis_count_new+ " Unit");
  //  $("#Cancel").text(response.count.workhis_count_cancel+" Unit");
  },
  error: function(xhr, status, error) {
  // Handle errors
  console.log("Error: " + error);
  }
  });
  }
  </script>
{% endblock content%}